### ISSUE TITLE
Push artifacts to maven central

### ISSUE THREAD

**Issue by unicolet** [transceptor-technology/java-qpack#6]
The build artifact should be available on maven central repository, thus allowing easy pulling from other projects without having to manually copy jars around :-)

Guide: https://maven.apache.org/repository/index.html

**Comment by unicolet** [comment]
Guidelines for pushing: https://central.sonatype.org/pages/ossrh-guide.html

**Comment by joente** [comment]
QPack is now be available on ossrh (the `0.0-SNAPSHOT` version)

https://oss.sonatype.org/#nexus-search;quick~qpack

**Comment by unicolet** [comment]
@joente nice! Let me give it a try :-)

**Comment by unicolet** [comment]
@joente seems to be there:

https://oss.sonatype.org/content/groups/public/technology/transceptor/java-qpack/0.0-SNAPSHOT/

can you upload a `stable` release, i.e. without `SNAPSHOT` in the release number? Thanks :-)

**Comment by joente** [comment]
```
Uploading to ossrh: https://oss.sonatype.org/service/local/staging/deploy/maven2/technology/transceptor/java-qpack/0.0/java-qpack-0.0.jar
Uploaded to ossrh: https://oss.sonatype.org/service/local/staging/deploy/maven2/technology/transceptor/java-qpack/0.0/java-qpack-0.0.jar (9.1 kB at 298 B/s)
Uploading to ossrh: https://oss.sonatype.org/service/local/staging/deploy/maven2/technology/transceptor/java-qpack/0.0/java-qpack-0.0.pom
Uploaded to ossrh: https://oss.sonatype.org/service/local/staging/deploy/maven2/technology/transceptor/java-qpack/0.0/java-qpack-0.0.pom (3.7 kB at 3.1 kB/s)
Downloading from ossrh: https://oss.sonatype.org/service/local/staging/deploy/maven2/technology/transceptor/java-qpack/maven-metadata.xml
Uploading to ossrh: https://oss.sonatype.org/service/local/staging/deploy/maven2/technology/transceptor/java-qpack/maven-metadata.xml
Uploaded to ossrh: https://oss.sonatype.org/service/local/staging/deploy/maven2/technology/transceptor/java-qpack/maven-metadata.xml (308 B at 188 B/s)
```

It seems that a proxy is used, maybe it takes some time for the package to appear in the repository?

**Comment by unicolet** [comment]
@joente that's been pushed to staging, I think you need some extra step to move from staging to release: https://central.sonatype.org/pages/releasing-the-deployment.html

**Comment by joente** [comment]
@unicolet, thanks, I expected to find the package in the staging repo and did not find it; but probably I'm missing something. I will read the document and see if it works, I'll let you know :-)

**Comment by joente** [comment]
@unicolet, I'm a bit confused about this part in the documentation: (since our `pom.xml` has the `nexus-staging-plugin` configured, I would expect an automated release)

> ### Nexus Staging Maven Plugin for Deployment and Release
>The Nexus Staging Maven Plugin is the recommended way to deploy your components to OSSRH and release them to the Central Repository. To configure it simply add the plugin to your Maven pom.xml.
> ```
> <build>
> <plugins>
> ...
> <plugin>
>   <groupId>org.sonatype.plugins</groupId>
>   <artifactId>nexus-staging-maven-plugin</artifactId>
>   <version>1.6.7</version>
>   <extensions>true</extensions>
>   <configuration>
>      <serverId>ossrh</serverId>
>      <nexusUrl>https://oss.sonatype.org/</nexusUrl>
>      <autoReleaseAfterClose>true</autoReleaseAfterClose>
>   </configuration>
> </plugin>
> ```
> If your version is a release version (does not end in -SNAPSHOT) and with this setup in place, you can > run a deployment to OSSRH and an automated release to the Central Repository with the usual:
> ```
> mvn clean deploy
> ```

I also found that it could take at least minutes to a couple of hours before things are synchronized? Any change that it just takes time?

**Comment by unicolet** [comment]
@joente I can find the artifact in staging:

https://oss.sonatype.org/content/repositories/staging/technology/transceptor/java-qpack/

and I can download the snapshot using mvn, so it does look like one extra step is missing. I've never deployed to the public repos so I'm a newbie too :-)

**Comment by joente** [comment]
I guess that is still the `0.0-SNAPSHOT`, and not the `0.0` which I uploaded later. The latter should be available in `..service/local/staging/`, not `..content/repositories/`

**Comment by unicolet** [comment]
> I guess that is still the 0.0-SNAPSHOT

you're right, sorry my bad :-)

**Comment by joente** [comment]
The package is available here: https://oss.sonatype.org/service/local/repositories/technologytransceptor-1000/content/technology/transceptor/java-qpack/0.0/java-qpack-0.0.jar

**Comment by joente** [comment]
I see, some requirements are not met: 
- Javadoc
- Developer info in pom.xml
- sources.jar is missing
- signature is missing.

**Comment by joente** [comment]
Solved all the requirements and I think it worked now: https://oss.sonatype.org/service/local/repositories/releases/content/technology/transceptor/java-qpack/0.0/java-qpack-0.0.jar

**Comment by unicolet** [comment]
@joente great work! and thanks :-)

```
mvn -U  dependency:get -Dartifact=technology.transceptor:java-qpack:0.0
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:get (default-cli) @ standalone-pom ---
[INFO] Resolving technology.transceptor:java-qpack:jar:0.0 with transitive dependencies
Downloading: https://repo.maven.apache.org/maven2/technology/transceptor/java-qpack/0.0/java-qpack-0.0.pom
Downloaded: https://repo.maven.apache.org/maven2/technology/transceptor/java-qpack/0.0/java-qpack-0.0.pom (5.4 kB at 10 kB/s)
Downloading: https://repo.maven.apache.org/maven2/technology/transceptor/java-qpack/0.0/java-qpack-0.0.jar
Downloaded: https://repo.maven.apache.org/maven2/technology/transceptor/java-qpack/0.0/java-qpack-0.0.jar (9.4 kB at 121 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.769 s
[INFO] Finished at: 2018-08-17T12:58:13+02:00
[INFO] Final Memory: 17M/295M
[INFO] ------------------------------------------------------------------------
```
